HW Advanced is done ☺
IrinaKimeisha/TAF pull request #4
Opened 2022-10-21 22:26 UTC by IrinaKimeisha

2022-10-30 11:32 UTC, wildpioneer requested changes

2022-10-30 11:32 UTC, wildpioneer commented on src/test/java/tests/HerokuAppTestHW.java
> +        Assert.assertEquals(wait.waitForExists(By.id("uploaded-files")).getText(), "Снимок экрана (52).jpeg");
Никогда не используй названия файлов на языке отличном от английского и с пробелами - это принесет много проблем - у меня вот например тест не прошел из-за этого

2022-10-31 16:15 UTC, IrinaKimeisha commented on src/test/java/tests/HerokuAppTestHW.java
> +        Assert.assertEquals(wait.waitForExists(By.id("uploaded-files")).getText(), "Снимок экрана (52).jpeg");
исправлено, тест прошел ☺

2022-11-08 19:35 UTC, wildpioneer commented
Проверено

2022-11-08 19:35 UTC, closed without merging