PageObject_Simple_hw
IrinaKimeisha/TAF pull request #5
Opened 2022-10-22 22:12 UTC by IrinaKimeisha

что-то на татарском

2022-10-30 11:34 UTC, wildpioneer commented
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/8968693/198876295-16330ef8-e446-4bc0-8851-14b4b9bba202.png">

2022-10-30 11:40 UTC, wildpioneer requested changes

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/steps/CheckoutStep.java
> +    public void continueButton() {
А почему методы ниже не возвращают никакого значения?

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/tests/CheckoutTest.java
> +    @Test
Пустая строка должна быть

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/tests/CheckoutTest.java
> +    @Test
Форматирование - не лепи все в одну кучу

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/tests/CheckoutTest.java
> +        Assert.assertTrue(checkoutPage.isPageOpened());
checkoutPage - нигде не была проинициализирована - соответственно она будет Null

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/pages/CataloguePage.java
> +    private final By headerTitleLabelLocator = By.xpath("//*[@id='header_container']/div[2]/span"); //показатель того, что страница каталога открыта
div[2] - точно нужно здесь?

2022-10-30 11:40 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +public class CheckoutPage extends BasePage {
Т.е. в одно страницу ты вместила весь путь от добавления товара до оплаты?

2022-11-14 12:33 UTC, IrinaKimeisha commented on src/test/java/tests/CheckoutTest.java
> +    @Test
принято

2022-11-14 12:33 UTC, IrinaKimeisha commented on src/test/java/tests/CheckoutTest.java
> +    @Test
стараюсь

2022-11-14 12:33 UTC, IrinaKimeisha commented on src/test/java/pages/CataloguePage.java
> +    private final By headerTitleLabelLocator = By.xpath("//*[@id='header_container']/div[2]/span"); //показатель того, что страница каталога открыта
исправлено

2022-11-14 12:42 UTC, wildpioneer commented
Проверил изменения

2022-11-14 12:42 UTC, closed without merging